name: "CodeQL"
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize the CodeQL tools
      uses: github/codeql-action/init@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
